// Syllabus data — SSC CGL Tier 1, Tier 2 Paper 1, Tier 2 Paper 3
// Each topic: { t: "name", r: true }  -> r marks a foundational/related topic
// (not asked directly, but needed to understand a core topic)

const DATA = {
  tier1: {
    label: "Tier 1",
    short: "T1",
    pattern: [
      ["Format", "Single paper, CBT"],
      ["Questions", "100 (4 × 25)"],
      ["Marks", "200 (2 per Q)"],
      ["Duration", "60 minutes"],
      ["Negative marking", "−0.50 / wrong"],
    ],
    sections: [
      { name: "General Intelligence & Reasoning", meta: "25 Qs · 50 marks", topics: [
        { t: "Analogy (semantic, number, figural)" },
        { t: "Classification / Odd One Out" },
        { t: "Series — number, alphabet, alphanumeric" },
        { t: "Coding–Decoding" },
        { t: "Blood Relations" },
        { t: "Direction & Distance Sense" },
        { t: "Ranking, Order & Sequence" },
        { t: "Alphabet Test / Word arrangement" },
        { t: "Syllogism" },
        { t: "Venn Diagrams" },
        { t: "Matrix-based reasoning" },
        { t: "Missing Number / Figure" },
        { t: "Word Formation" },
        { t: "Sitting Arrangement — linear & circular" },
        { t: "Puzzle (box, floor, age-based)" },
        { t: "Statement–Conclusion / Statement–Argument" },
        { t: "Cube and Dice" },
        { t: "Mirror & Water Images" },
        { t: "Paper Folding & Cutting" },
        { t: "Embedded Figures / Figure Completion" },
        { t: "Counting Figures" },
        { t: "Clock-based reasoning", r: 1 },
        { t: "Calendar-based reasoning", r: 1 },
      ]},
      { name: "Quantitative Aptitude", meta: "25 Qs · 50 marks", topics: [
        { t: "Number System basics", r: 1 },
        { t: "HCF & LCM" },
        { t: "Simplification (BODMAS, surds & indices)" },
        { t: "Percentage" },
        { t: "Profit, Loss & Discount" },
        { t: "Simple & Compound Interest" },
        { t: "Ratio, Proportion & Partnership" },
        { t: "Average" },
        { t: "Time & Work (incl. pipes & cisterns)" },
        { t: "Time, Speed & Distance (incl. boats & trains)" },
        { t: "Mixture & Alligation" },
        { t: "Basic Algebraic identities", r: 1 },
        { t: "Linear & quadratic equations" },
        { t: "Geometry — lines, angles, triangles" },
        { t: "Geometry — circles & polygons" },
        { t: "Mensuration — 2D figures" },
        { t: "Mensuration — 3D solids" },
        { t: "Trigonometric ratios & identities", r: 1 },
        { t: "Heights & Distances" },
        { t: "Data Interpretation — bar/pie/line graphs, tables" },
        { t: "Basic Statistics — mean, median, mode", r: 1 },
        { t: "Coordinate Geometry basics", r: 1 },
      ]},
      { name: "English Comprehension", meta: "25 Qs · 50 marks", topics: [
        { t: "Reading Comprehension passages" },
        { t: "Cloze Test" },
        { t: "Fill in the Blanks" },
        { t: "Spotting Errors" },
        { t: "Sentence Improvement" },
        { t: "Sentence Rearrangement (Para Jumbles)" },
        { t: "Synonyms" },
        { t: "Antonyms" },
        { t: "One Word Substitution" },
        { t: "Idioms & Phrasal Verbs" },
        { t: "Spelling Correction" },
        { t: "Active ↔ Passive Voice" },
        { t: "Direct ↔ Indirect (Narration)" },
        { t: "Parts of Speech & basic grammar rules", r: 1 },
        { t: "Daily vocabulary building", r: 1 },
      ]},
      { name: "General Awareness", meta: "25 Qs · 50 marks", topics: [
        { t: "Ancient & Medieval Indian History" },
        { t: "Modern India & Freedom Struggle" },
        { t: "Indian Geography — physical & economic" },
        { t: "World Geography basics" },
        { t: "Indian Polity & Constitution" },
        { t: "Governance & Public Administration basics" },
        { t: "Indian Economy — basic concepts" },
        { t: "Physics — school-level concepts" },
        { t: "Chemistry — school-level concepts" },
        { t: "Biology — school-level concepts" },
        { t: "Static GK — books & authors, awards, schemes" },
        { t: "Static GK — important days, sports, capitals & currencies" },
        { t: "Current Affairs — last 6–12 months" },
        { t: "Basic Computer Awareness", r: 1 },
      ]},
    ]
  },

  tier2p1: {
    label: "Tier 2 · Paper 1",
    short: "T2 P1",
    pattern: [
      ["Format", "Compulsory · 3 sessions"],
      ["Session 1", "Maths + Reasoning · 60 Qs · 60 min"],
      ["Session 2", "English + Gen. Awareness · 70 Qs · 60 min"],
      ["Session 3", "Computer (20Q) + Data Entry · ~30 min"],
      ["Negative marking", "−1 / wrong (Modules I & II)"],
    ],
    sections: [
      { name: "Mathematical Abilities", meta: "30 Qs · Session 1", topics: [
        { t: "Number System — advanced (divisibility, remainders)", r: 1 },
        { t: "HCF, LCM & Simplification — higher difficulty" },
        { t: "Percentage, Profit/Loss, SI–CI — advanced problems" },
        { t: "Ratio, Average, Mixture & Alligation — advanced" },
        { t: "Time, Work, Speed & Distance — advanced" },
        { t: "Algebra — polynomials, identities, linear/quadratic systems" },
        { t: "Geometry — triangles, circles, quadrilaterals (theorem-based)" },
        { t: "Mensuration — advanced 2D & 3D combinations" },
        { t: "Trigonometry — identities & heights/distances, advanced" },
        { t: "Statistics — mean, median, mode, standard deviation" },
        { t: "Data Interpretation — multi-source, caselet-based" },
        { t: "Coordinate Geometry — lines & basic conics", r: 1 },
      ]},
      { name: "Reasoning & General Intelligence", meta: "30 Qs · Session 1", topics: [
        { t: "Analogy, Classification & Series — higher difficulty" },
        { t: "Coding–Decoding — advanced patterns" },
        { t: "Blood Relations & Direction Sense — multi-step" },
        { t: "Complex Puzzles (box/floor/schedule based)" },
        { t: "Multi-person Sitting Arrangement" },
        { t: "Syllogism & Statement-based reasoning — advanced" },
        { t: "Matrix & Word-based reasoning" },
        { t: "Non-verbal: mirror/water images, folding, embedded figures" },
        { t: "Cube, Dice & Figure counting — advanced" },
        { t: "Logical Venn Diagrams & set-based reasoning" },
        { t: "Analytical & Decision-making reasoning" },
      ]},
      { name: "English Language & Comprehension", meta: "45 Qs · Session 2", topics: [
        { t: "Reading Comprehension — longer, inference-based passages" },
        { t: "Cloze Test & Fill in the Blanks — advanced vocabulary" },
        { t: "Spotting Errors & Sentence Improvement — advanced" },
        { t: "Para Jumbles / Sentence Rearrangement" },
        { t: "Synonyms, Antonyms & One Word Substitution — advanced" },
        { t: "Idioms, Phrasal Verbs & Homophones" },
        { t: "Active/Passive & Direct/Indirect — advanced constructions" },
        { t: "Confusable words & commonly misused words", r: 1 },
        { t: "Advanced grammar rules (tense, modals, articles)", r: 1 },
      ]},
      { name: "General Awareness", meta: "25 Qs · Session 2", topics: [
        { t: "History, Polity & Economy — deeper coverage" },
        { t: "Geography — India & World, deeper coverage" },
        { t: "Science — Physics, Chemistry, Biology, deeper coverage" },
        { t: "Static GK — comprehensive (schemes, awards, sports, culture)" },
        { t: "Current Affairs — last 12 months, national & international" },
      ]},
      { name: "Computer Knowledge Test", meta: "20 Qs · Session 3", topics: [
        { t: "Computer basics — hardware & software" },
        { t: "History & generations of computers", r: 1 },
        { t: "Operating System basics (Windows)" },
        { t: "MS Word — features & shortcuts" },
        { t: "MS Excel — formulas & features" },
        { t: "MS PowerPoint — features & shortcuts" },
        { t: "Internet, Web browsers & search engines" },
        { t: "Email — etiquette & functions" },
        { t: "Networking basics (LAN/WAN, protocols)", r: 1 },
        { t: "Cyber security & safety basics" },
        { t: "Number system for computers (binary/hex)", r: 1 },
        { t: "Common keyboard shortcuts" },
      ]},
      { name: "Data Entry Speed Test", meta: "1 task · Session 3", topics: [
        { t: "Touch-typing accuracy drills" },
        { t: "Speed building toward 2000 key depressions in 15 min" },
        { t: "Practice on the actual SSC typing interface/format", r: 1 },
      ]},
    ]
  },

  tier2p3: {
    label: "Tier 2 · Paper 3",
    short: "T2 P3",
    pattern: [
      ["Format", "For AAO / AAO(IA&AD) posts only"],
      ["Sections", "Part A: Finance & Accounts · Part B: Economics & Governance"],
      ["Duration", "2 hours"],
      ["Negative marking", "−1 / wrong"],
    ],
    sections: [
      { name: "Part A — Finance and Accounts", meta: "~80 marks", topics: [
        { t: "Nature & scope of Financial Accounting" },
        { t: "Basic accounting concepts & conventions" },
        { t: "Capital vs Revenue expenditure/receipts" },
        { t: "Contingent Assets & Contingent Liabilities" },
        { t: "Preparation of Financial Statements" },
        { t: "Single Entry vs Double Entry bookkeeping", r: 1 },
        { t: "Bank Reconciliation Statement" },
        { t: "Depreciation — methods & accounting" },
        { t: "Rectification of Errors" },
        { t: "Bills of Exchange" },
        { t: "Consignment & Joint Venture accounts", r: 1 },
        { t: "Inventory valuation methods" },
        { t: "Non-Profit Organisation accounts" },
        { t: "Basics of Company Accounts", r: 1 },
      ]},
      { name: "Part B — Economics and Governance", meta: "~120 marks", topics: [
        { t: "Comptroller & Auditor General of India — role & functions" },
        { t: "Finance Commission of India — role & functions" },
        { t: "Basic concepts of Economics — micro vs macro", r: 1 },
        { t: "Positive vs Normative Economics", r: 1 },
        { t: "Theory of Demand & Supply" },
        { t: "Elasticity of Demand & Supply" },
        { t: "Market Equilibrium & price determination" },
        { t: "Theory of Production — factors & laws of production" },
        { t: "Cost concepts & cost curves", r: 1 },
        { t: "Forms of Market — perfect competition" },
        { t: "Forms of Market — monopoly, monopolistic & oligopoly", r: 1 },
        { t: "Indian Economy — nature, structure & demographic features" },
        { t: "Poverty & Unemployment in India" },
        { t: "Infrastructure — energy, transport & communication" },
        { t: "Economic Reforms since 1991 (Liberalisation, Privatisation, Globalisation)" },
        { t: "Disinvestment policy" },
        { t: "Money & Banking — RBI functions" },
        { t: "Monetary Policy & Fiscal Policy" },
        { t: "Union Budget process & terminology" },
        { t: "Banking sector reforms & financial inclusion" },
        { t: "Role of Information Technology in Governance" },
      ]},
    ]
  }
};
