// Syllabus data — SSC CGL Tier 1, Tier 2 Paper 1, Tier 2 Paper 2 (Statistics)
// Each topic: { t: "name", r: true }  -> r marks a foundational/related topic
// (not asked directly, but needed to understand a core topic)

const DATA = {
  tier1: {
    label: "Tier 1",
    short: "T1",
    pattern: [
      ["Format", "Single paper, CBT"],
      ["Questions", "100 (4 × 25)"],
      ["Marks", "200 (2 per Q)"],
      ["Duration", "60 minutes"],
      ["Negative marking", "−0.50 / wrong"],
    ],
    sections: [
      { name: "General Intelligence & Reasoning", meta: "25 Qs · 50 marks", topics: [
        { t: "Analogy (semantic, number, figural)" },
        { t: "Classification / Odd One Out" },
        { t: "Series — number, alphabet, alphanumeric" },
        { t: "Coding–Decoding" },
        { t: "Blood Relations" },
        { t: "Direction & Distance Sense" },
        { t: "Ranking, Order & Sequence" },
        { t: "Alphabet Test / Word arrangement" },
        { t: "Syllogism" },
        { t: "Venn Diagrams" },
        { t: "Matrix-based reasoning" },
        { t: "Missing Number / Figure" },
        { t: "Word Formation" },
        { t: "Sitting Arrangement — linear & circular" },
        { t: "Puzzle (box, floor, age-based)" },
        { t: "Statement–Conclusion / Statement–Argument" },
        { t: "Cube and Dice" },
        { t: "Mirror & Water Images" },
        { t: "Paper Folding & Cutting" },
        { t: "Embedded Figures / Figure Completion" },
        { t: "Counting Figures" },
        { t: "Clock-based reasoning", r: 1 },
        { t: "Calendar-based reasoning", r: 1 },
      ]},
      { name: "Quantitative Aptitude", meta: "25 Qs · 50 marks", topics: [
        { t: "Number System basics", r: 1 },
        { t: "HCF & LCM" },
        { t: "Simplification (BODMAS, surds & indices)" },
        { t: "Percentage" },
        { t: "Profit, Loss & Discount" },
        { t: "Simple & Compound Interest" },
        { t: "Ratio, Proportion & Partnership" },
        { t: "Average" },
        { t: "Time & Work (incl. pipes & cisterns)" },
        { t: "Time, Speed & Distance (incl. boats & trains)" },
        { t: "Mixture & Alligation" },
        { t: "Basic Algebraic identities", r: 1 },
        { t: "Linear & quadratic equations" },
        { t: "Geometry — lines, angles, triangles" },
        { t: "Geometry — circles & polygons" },
        { t: "Mensuration — 2D figures" },
        { t: "Mensuration — 3D solids" },
        { t: "Trigonometric ratios & identities", r: 1 },
        { t: "Heights & Distances" },
        { t: "Data Interpretation — bar/pie/line graphs, tables" },
        { t: "Basic Statistics — mean, median, mode", r: 1 },
        { t: "Coordinate Geometry basics", r: 1 },
      ]},
      { name: "English Comprehension", meta: "25 Qs · 50 marks", topics: [
        { t: "Reading Comprehension passages" },
        { t: "Cloze Test" },
        { t: "Fill in the Blanks" },
        { t: "Spotting Errors" },
        { t: "Sentence Improvement" },
        { t: "Sentence Rearrangement (Para Jumbles)" },
        { t: "Synonyms" },
        { t: "Antonyms" },
        { t: "One Word Substitution" },
        { t: "Idioms & Phrasal Verbs" },
        { t: "Spelling Correction" },
        { t: "Active ↔ Passive Voice" },
        { t: "Direct ↔ Indirect (Narration)" },
        { t: "Parts of Speech & basic grammar rules", r: 1 },
        { t: "Daily vocabulary building", r: 1 },
      ]},
      { name: "General Awareness", meta: "25 Qs · 50 marks", topics: [
        { t: "Ancient & Medieval Indian History" },
        { t: "Modern India & Freedom Struggle" },
        { t: "Indian Geography — physical & economic" },
        { t: "World Geography basics" },
        { t: "Indian Polity & Constitution" },
        { t: "Governance & Public Administration basics" },
        { t: "Indian Economy — basic concepts" },
        { t: "Physics — school-level concepts" },
        { t: "Chemistry — school-level concepts" },
        { t: "Biology — school-level concepts" },
        { t: "Static GK — books & authors, awards, schemes" },
        { t: "Static GK — important days, sports, capitals & currencies" },
        { t: "Current Affairs — last 6–12 months" },
        { t: "Basic Computer Awareness", r: 1 },
      ]},
    ]
  },

  tier2p1: {
    label: "Tier 2 · Paper 1",
    short: "T2 P1",
    pattern: [
      ["Format", "Compulsory · 3 sessions"],
      ["Session 1", "Maths + Reasoning · 60 Qs · 60 min"],
      ["Session 2", "English + Gen. Awareness · 70 Qs · 60 min"],
      ["Session 3", "Computer (20Q) + Data Entry · ~30 min"],
      ["Negative marking", "−1 / wrong (Modules I & II)"],
    ],
    sections: [
      { name: "Mathematical Abilities", meta: "30 Qs · Session 1", topics: [
        { t: "Number System — advanced (divisibility, remainders)", r: 1 },
        { t: "HCF, LCM & Simplification — higher difficulty" },
        { t: "Percentage, Profit/Loss, SI–CI — advanced problems" },
        { t: "Ratio, Average, Mixture & Alligation — advanced" },
        { t: "Time, Work, Speed & Distance — advanced" },
        { t: "Algebra — polynomials, identities, linear/quadratic systems" },
        { t: "Geometry — triangles, circles, quadrilaterals (theorem-based)" },
        { t: "Mensuration — advanced 2D & 3D combinations" },
        { t: "Trigonometry — identities & heights/distances, advanced" },
        { t: "Statistics — mean, median, mode, standard deviation" },
        { t: "Data Interpretation — multi-source, caselet-based" },
        { t: "Coordinate Geometry — lines & basic conics", r: 1 },
      ]},
      { name: "Reasoning & General Intelligence", meta: "30 Qs · Session 1", topics: [
        { t: "Analogy, Classification & Series — higher difficulty" },
        { t: "Coding–Decoding — advanced patterns" },
        { t: "Blood Relations & Direction Sense — multi-step" },
        { t: "Complex Puzzles (box/floor/schedule based)" },
        { t: "Multi-person Sitting Arrangement" },
        { t: "Syllogism & Statement-based reasoning — advanced" },
        { t: "Matrix & Word-based reasoning" },
        { t: "Non-verbal: mirror/water images, folding, embedded figures" },
        { t: "Cube, Dice & Figure counting — advanced" },
        { t: "Logical Venn Diagrams & set-based reasoning" },
        { t: "Analytical & Decision-making reasoning" },
      ]},
      { name: "English Language & Comprehension", meta: "45 Qs · Session 2", topics: [
        { t: "Reading Comprehension — longer, inference-based passages" },
        { t: "Cloze Test & Fill in the Blanks — advanced vocabulary" },
        { t: "Spotting Errors & Sentence Improvement — advanced" },
        { t: "Para Jumbles / Sentence Rearrangement" },
        { t: "Synonyms, Antonyms & One Word Substitution — advanced" },
        { t: "Idioms, Phrasal Verbs & Homophones" },
        { t: "Active/Passive & Direct/Indirect — advanced constructions" },
        { t: "Confusable words & commonly misused words", r: 1 },
        { t: "Advanced grammar rules (tense, modals, articles)", r: 1 },
      ]},
      { name: "General Awareness", meta: "25 Qs · Session 2", topics: [
        { t: "History, Polity & Economy — deeper coverage" },
        { t: "Geography — India & World, deeper coverage" },
        { t: "Science — Physics, Chemistry, Biology, deeper coverage" },
        { t: "Static GK — comprehensive (schemes, awards, sports, culture)" },
        { t: "Current Affairs — last 12 months, national & international" },
      ]},
      { name: "Computer Knowledge Test", meta: "20 Qs · Session 3", topics: [
        { t: "Computer basics — hardware & software" },
        { t: "History & generations of computers", r: 1 },
        { t: "Operating System basics (Windows)" },
        { t: "MS Word — features & shortcuts" },
        { t: "MS Excel — formulas & features" },
        { t: "MS PowerPoint — features & shortcuts" },
        { t: "Internet, Web browsers & search engines" },
        { t: "Email — etiquette & functions" },
        { t: "Networking basics (LAN/WAN, protocols)", r: 1 },
        { t: "Cyber security & safety basics" },
        { t: "Number system for computers (binary/hex)", r: 1 },
        { t: "Common keyboard shortcuts" },
      ]},
      { name: "Data Entry Speed Test", meta: "1 task · Session 3", topics: [
        { t: "Touch-typing accuracy drills" },
        { t: "Speed building toward 2000 key depressions in 15 min" },
        { t: "Practice on the actual SSC typing interface/format", r: 1 },
      ]},
    ]
  },

  tier2p2: {
    label: "Tier 2 · Paper 2",
    short: "T2 P2",
    pattern: [
      ["Format", "Statistics — for JSO posts only"],
      ["Questions", "100 · 200 marks (2 per Q)"],
      ["Duration", "2 hours"],
      ["Negative marking", "−0.50 / wrong"],
    ],
    sections: [
      { name: "Collection, Classification & Presentation of Statistical Data", meta: "", topics: [
        { t: "Primary and Secondary data" },
        { t: "Methods of data collection" },
        { t: "Tabulation of data" },
        { t: "Diagrammatic presentation of data" },
        { t: "Graphs and charts" },
        { t: "Frequency distributions" },
        { t: "Levels of measurement — nominal, ordinal, interval, ratio", r: 1 },
      ]},
      { name: "Measures of Central Tendency", meta: "", topics: [
        { t: "Arithmetic Mean" },
        { t: "Geometric Mean & Harmonic Mean" },
        { t: "Median" },
        { t: "Mode" },
        { t: "Partition values — Quartiles" },
        { t: "Partition values — Deciles & Percentiles" },
      ]},
      { name: "Measures of Dispersion", meta: "", topics: [
        { t: "Range" },
        { t: "Quartile Deviation" },
        { t: "Mean Deviation" },
        { t: "Standard Deviation" },
        { t: "Measures of relative dispersion — Coefficient of Variation" },
      ]},
      { name: "Moments, Skewness and Kurtosis", meta: "", topics: [
        { t: "Raw and central moments & their relationship" },
        { t: "Meaning of skewness" },
        { t: "Measures of skewness" },
        { t: "Meaning of kurtosis" },
        { t: "Measures of kurtosis" },
      ]},
      { name: "Correlation and Regression", meta: "", topics: [
        { t: "Scatter diagram" },
        { t: "Simple correlation coefficient (Karl Pearson)" },
        { t: "Spearman's rank correlation" },
        { t: "Measures of association of attributes" },
        { t: "Simple regression lines" },
        { t: "Multiple regression" },
        { t: "Multiple and partial correlation (three variables)" },
      ]},
      { name: "Probability Theory", meta: "", topics: [
        { t: "Meaning of probability" },
        { t: "Different definitions of probability — classical, relative frequency, axiomatic" },
        { t: "Conditional probability" },
        { t: "Compound probability" },
        { t: "Bayes' theorem" },
        { t: "Basic set theory & permutations/combinations", r: 1 },
      ]},
      { name: "Random Variable and Probability Distributions", meta: "", topics: [
        { t: "Random variable & probability functions" },
        { t: "Expectation and variance of a random variable" },
        { t: "Higher moments of a random variable" },
        { t: "Binomial distribution" },
        { t: "Poisson distribution" },
        { t: "Normal distribution" },
        { t: "Exponential distribution" },
        { t: "Joint probability distribution (two variables)" },
      ]},
      { name: "Sampling Theory", meta: "", topics: [
        { t: "Population & sample; parameter & statistic" },
        { t: "Sampling and non-sampling errors" },
        { t: "Simple random sampling" },
        { t: "Stratified sampling" },
        { t: "Multistage & multiphase sampling" },
        { t: "Cluster sampling & systematic sampling" },
        { t: "Purposive, convenience & quota sampling" },
        { t: "Sampling distribution (statement only)" },
        { t: "Sample size decisions" },
      ]},
      { name: "Statistical Inference", meta: "", topics: [
        { t: "Point estimation and interval estimation" },
        { t: "Properties of a good estimator" },
        { t: "Method of moments" },
        { t: "Maximum likelihood method" },
        { t: "Method of least squares" },
        { t: "Testing of hypothesis — basic concepts" },
        { t: "Small sample and large sample tests" },
        { t: "Tests of significance based on Z statistic" },
        { t: "Tests of significance based on t statistic" },
        { t: "Tests of significance based on Chi-square statistic" },
        { t: "Tests of significance based on F statistic" },
        { t: "Confidence intervals" },
      ]},
      { name: "Analysis of Variance", meta: "", topics: [
        { t: "Analysis of one-way classified data" },
        { t: "Analysis of two-way classified data" },
      ]},
      { name: "Time Series Analysis", meta: "", topics: [
        { t: "Components of time series" },
        { t: "Determination of trend by different methods" },
        { t: "Measurement of seasonal variation by different methods" },
      ]},
      { name: "Index Numbers", meta: "", topics: [
        { t: "Meaning and uses of index numbers" },
        { t: "Construction of index numbers" },
        { t: "Types of index numbers" },
        { t: "Wholesale Price Index Number (WPI)" },
        { t: "Consumer Price Index Number (CPI)" },
        { t: "Index of Industrial Production (IIP)" },
        { t: "Cost of Living Index Number" },
        { t: "Uses and limitations of index numbers" },
      ]},
    ]
  }
};
